### ISSUE TITLE
Readme instructions for how to set up database

### ISSUE THREAD

**Issue by lunarraid** [jdnichollsc/adventure-closure#4]
The readme for the api does not include instructions for initializing the database, nor that this is a requirement.

**Comment by jdnichollsc** [comment]
oh the database is initialized automatically, using migrations by default, but let me put that from README, thanks! 👍

**Comment by lunarraid** [comment]
Odd, I tried that and it kept complaining that there was no database called 'my_database'

**Comment by jdnichollsc** [comment]
Oh sorry for that, I created the database from terminal and now is pointing to a external DB, let me add that previous step running locally

**Comment by jdnichollsc** [comment]
@lunarraid I updated the readme with some instructions, let me know if this command works for you, thanks for your help! https://github.com/jdnichollsc/adventure-closure#running-the-api
